import time
import psutil
import logging
from airllm import AutoModel

# Configure basic logging to observe the process and layer-by-layer progression
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Same massive 70B parameter model used in the baseline script
MODEL_ID = "meta-llama/Llama-2-70b-hf"

def get_memory_usage():
    """Returns current process memory usage in GB."""
    process = psutil.Process()
    return process.memory_info().rss / (1024 ** 3)

def run_airllm():
    logger.info(f"--- Starting AirLLM Run for {MODEL_ID} on CPU ---")
    logger.info(f"Initial Memory Usage: {get_memory_usage():.2f} GB")

    try:
        logger.info(f"Initializing AirLLM model structure for ({MODEL_ID})...")
        logger.info("Unlike the baseline, AirLLM will NOT load the entire model into RAM.")
        logger.info("It streams layers one-by-one from disk during inference to save memory.")
        
        start_load_time = time.time()
        
        # Load the model via AirLLM AutoModel
        # This only prepares the layer swapping mechanism; it does not load massive weights into RAM.
        model = AutoModel.from_pretrained(MODEL_ID)
        
        end_load_time = time.time()
        logger.info(f"AirLLM Setup successful in {end_load_time - start_load_time:.2f} seconds.")
        logger.info(f"Memory Usage after setup: {get_memory_usage():.2f} GB (Notice this is a tiny fraction of the 140GB needed for the baseline!)")
        
        prompt = ["Explain the theory of relativity in simple terms."]
        logger.info(f"Tokenizing prompt: {prompt[0]}")
        
        # Tokenize the input text
        input_tokens = model.tokenizer(
            prompt,
            return_tensors="pt",
            return_attention_mask=False,
            truncation=True,
            max_length=128,
            padding=False
        )
        
        logger.info("Starting generation process...")
        logger.info("You should now see AirLLM's internal logs indicating layer-by-layer disk swapping processing.")
        
        start_gen_time = time.time()
        
        # Execute generation. 
        # Note: We pass standard CPU tensors to model.generate(). We explicitly do not use .cuda()
        # to ensure the model runs solely on the CPU memory space, highlighting AirLLM's CPU capabilities.
        generation_output = model.generate(
            input_tokens['input_ids'], 
            max_new_tokens=20,
            use_cache=True,
            return_dict_in_generate=True
        )
        
        end_gen_time = time.time()
        logger.info("Generation complete!")
        
        # Decode and print the output
        output_text = model.tokenizer.decode(generation_output.sequences[0], skip_special_tokens=True)
        
        print("\n" + "="*60)
        print("FINAL OUTPUT GENERATED BY AIRLLM:")
        print("="*60)
        print(output_text)
        print("="*60)
        
        print(f"\nFinal CPU Metrics for AirLLM:")
        print(f"- Total Generation Time: {end_gen_time - start_gen_time:.2f} seconds.")
        print(f"- Approximate memory usage post-inference: {get_memory_usage():.2f} GB")
        print("SUCCESS: The model processed the prompt successfully on standard CPU without crashing the RAM!")

    except Exception as e:
        logger.error(f"An unexpected exception occurred: {e}")
        logger.error("Ensure you have installed airllm via 'pip install airllm' and have access to the Hugging Face model.")

if __name__ == "__main__":
    run_airllm()
